### PR TITLE
Backend setup

### PR DESCRIPTION
**Pull request by FerdinandSpeer**
Made basic CRUD Setup for backend

### CODE REVIEW

**Review by Phaete — CHANGES_REQUESTED** [review]
Please check your test coverage!

**Review by sieberss — COMMENTED** [review]
Do you really need a DTO object?
For only leaving out a random ID and keeping a lot of other properties this looks like superflous code duplication for me.

**Review by RicardoCreates — APPROVED** [review]
LGTM!

**Review by Phaete — APPROVED** [review]
Thanks for adding tests and reaching the goal of 80% coverage.
Keep up the good work!

**Pull request merged**
